<!--<template>
     <li></li>
    <li class="item">
    <img src="#" class="item__photo" alt="Movie cover" />
    <p class="item__popularity">Popularity: 40.3</p>
    <h3 class="item__title">Being James Bond</h3>
    <router-link to="/details" class="btn item__btn">Full synopsis</router-link>
  </li>
</template>

<script>

</script>

<style lang="scss">
.content {
  &__btn::after {
    content: "";
    display: inline-block;
    height: 1rem;
    width: 1rem;
    margin-right: 0.7rem;

    background-image: url(../img/chevron-small-right.svg);
    background-size: cover;

    @supports (-webkit-mask-image: url()) or (mask-image: url()) {
      background-color: var(--color-secnodary-dark);
      -webkit-mask-image: url(../img/chevron-small-right.svg);
      -webkit-mask-size: cover;
      mask-image: url(../img/chevron-small-right.svg);
      mask-size: cover;
      background-image: none;
    }
  }
}
</style>-->
